
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { Database } from '@/types/supabase.types';

const SUPABASE_URL = "https://lxxslzdxzjoiptacurgn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx4eHNsemR4empvaXB0YWN1cmduIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1MDQ0MDgsImV4cCI6MjA2MzA4MDQwOH0.WwtwUP862S8yMKglJ93wzCCyPT0Cp_5ZD0dMxJYmas8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
